version: "3.8"

services:
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /urs/src/smart-brain-api
    environment:
      POSTGRES_USER: jackie
      POSTGRES_PASSWORD: Levalife2021
      POSTGRES_DB: smart-brain_docker
      POSTGRES_PORT: postgres

    links:
      - postgres 
    ports:
      - "3000:3000"
    volumes:
      - ./:/urs/src/smart-brain-api

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: jackie
      POSTGRES_PASSWORD: Levalife2021
      POSTGRES_DB: smart-brain_docker
      POSTGRES_PORT: postgres
    ports:
      - "5432:5432"



    